* Characters
** Introduction

This document provides a resource for the playable and non-boss characters in the game
Wawacraft:Evolved. Characters are given all the information I know about them, and if possible, some
images of them are placed.

Beware that some of the characters in this list may not be present in the game currently, but are
present within my imagination of the game and how it will turn out to be.

** Playable characters

*** Wawa

Wawa is by far the most popular character in the game of Wawacraft:Evolved, as well as its
predecessor, Wawacraft, and any other future media featuring him.

He is commonly depicted as a round-headed earless cat with 2 crimson blotches by his sides, with his
left blotch being the smaller of the two. He is also shown to be carrying a brandished hammer as his
tool.

**** Classification

On the *SELSEF* chart, Wawa is said to be an Altruistic-Sawg Rounded-Earless kitty. This means that
he values others over himself, and is charismatic. In appearance it means he is round headed and
earless.

**** In-game

In game, Wawa is a playable character that gives an up in the skills of Craftsmanship, Charmwork,
and Forgery. He is a character that many beginners play with and is quite stable as a development
build, however he is a character that in general is known to be very charm reliant and hard to
develop in any other skill.

Wawa players are characterized by their advanced craft and charm tree, with high understanding of
the game meta, but are prone to being vulnerable to weaknesses when faced with their natural
opposite, Uni and Floppa mains.

Due to their strength in charmcraft and forgery, they are quite excellent for anybody who would like
to instantiate trading and create a trading empire in their respective servers.

Main wawa if you want to be a jack of all trades through charms, and the resident merchant of you
and your friends' server.

**** History

Wawa originates from a meme that went popular around 2022 called Oh The Misery(not to be confused
with the WCEV Boss OTM), Kotaku, or Wawa cat, wherein an edit of an instagram post depicted Kotaku
as an earless cat with an angry face. This meme was also attributed to the Image Dragons song,
Enemy, wherein the signature lyric, Oh The Misery comes from.

He first appeared however in Wawacraft:Classic(Previously known simply as Wawacraft) as the first
playable character in the game. His first skin was the meme edit image scaled down to 128x128
resolution, and his more recognisable sprite image(the 17x17 sprite) came in around the area between
Wawacraft Beta 3 until Ember version, at which point his sprite texture was established to be the
solid appearance of the character for the rest of his lifetime in the series.

*** Uni

Uni is a black cat with a white beard, earful and silly. He is commonly depicted as a cat with grey
ear fuzz and a white beard, with his tool being a pickaxe.

There is an inside joke of Uni being quite stupid, which sprung from his wandering algorithm in
Wawacraft Classic not accounting for falling off of the edge of the map nor walking into walls for
extended amounts of time. He is well depicted as a mindless wandering, yet cute idiot who has no
issue walking into a tree repeatedly for several minutes.

**** Classification

On the *SELSEF* chart, Uni is classified to be a Neutral-Silly Rounded-Earful kitty. This means that
he does not consider himself nor others, and so is silly. He is also round-headed and sports ears,
which makes him an earful kitty.

**** In-game

In game, Uni gives an advantage in the Mining, Farming, and Endurance stats. He is often valued by players
who engage in PVP and ritual mining sessions. One can draw a parallel between the skills of Uni in
Wawacraft:Evolved and the playstyle of experienced players of /Minecraft/, since a majority of their
playtime consists of ritual mining sessions where they must endure dangerous monsters and engaging
in PVP battles.

Uni mains are characterized by their strong armour and great tools, since they are good in mining
and endurance. They are great mates for Wawa mains, as they can be great travel partners and make
use of the Wawa main's craftsmanship skills. They are usually not very reliant on charms, however it
is definitely a part of their playstyle if they wish to engage in PVP.

Uni mains are however often beated by mains of Floppa, because of their acquired power in Strength and
Woodworking. The natural enemy of an Uni main is a Floppa main.

In general however, Uni is great for beginning a route in mining resources, engaging in trades, and
creating charms, and beating the game's bosses.

Choose Uni if you want to become a great miner and trade in charms and ores, as well as beat bosses.

**** History

Uni originates from the meme spread around the internet, and mainly originating from discord of a
black cat with a white beard and very fluffy paws often humourously referred to as /Big Boobs/, with
his real name being Unicouniuni.

The joke of the original meme was a captioned-gif that read "His name is big boobs, search him up on
your school computer." In some other renditions, you are  instructed to search him up on the family
computer. The joke is that when searching the words "Big Boobs", you will be met with pornography
involving, well, big boobs, as opposed to the cute cat you were expecting. And on top of that, a
school or family computer implies that if you do search this, you'll have to explain that you
believed you'd be able to see a cute cat, which nobody would realistically believe.

Many will assume that nobody on the internet could fall for such a thing, but apparently searching
up "big boobs cat" returns the actual cat we were expecting, which is a very wholesome spin on the
originally grotesque joke of accidentally traumatizing whoever you sent this gif to with
porno.

However, the actual formula of putting something completely wholesome, and captioning that its name
is something very lewd is still a widespread formula across the internet, and more so on the
degenerate platform, Discord.

:Example:
[an image of a very cute animal, say a kitten or a puppy, or a lamb or fox]

His name is furry porn; search him up on your family computer.
:end:

Thankfully however, Uni as a whole has sort of grown out of that raunchy origin, and is now an
inside joke on the internet, reaching the famed status of many meme cats on the internet like
Floppa, Bingus, Jinx, and Maxwell.

He first appeared in Wawacraft Lockhart Version, and appears in Wawacraft:Evolved as well.

*** Floppa

Floppa is a playable character in the game, Wawacraft:Evolved known for being a strong character and
a very charismatic caracal.

He is often depicted as a caracal with a white beard and an axe as his main tool. Often times he may
be shown cooking, as it is one of the skills that players of Floppa have,

**** Classification

Floppa is classified on the *SELSEF* chart as Selfish-Sawg Carved-Earful. This means that he is
sawg, but also cares about himself before he does others. He also has a carved face and ears, making
him earful.

**** In-game

Floppa gives the skills of Woodworking, Strength, and Cooking. He is valued by players who wish to
experience the game in its most difficult form, wherein they usually do not use charms often and do
not craft many things. A Floppa main's best tool is his axe, trusty when chopping and best in
combat. They are the natural champions of PVP within the game, wherein they usually beat many other
players who require charms and grinding to get to their skill level.

Floppa mains are characterized by their primitive crafting tree and charm tree, as they do not craft
much or create much charms, because of the build of the character. Floppa keeps what is basically a
simple yet effective build and creates a simple, but effective playstyle. Their favourite thing to
do is to engage in missile tennis and PVP.

The one weakness that a Floppa main has is that his PVP-optimized build is often beaten by smart
Ploobie mains, with their high-jumps and crossbows, beating the beastly mains of Floppa.

Floppa is a good character to choose in general, being a strong character that encourages frequent
PVP and is a great mate for beating bosses for the server party, as well as the one who can create
soups and kits to heal players when fighting bosses.

**** History

Floppa originated from several memes of a large caracal called Floppa, that became popular online
around 2020. He appears in Wawacraft:Evolved but is nowhere to be seen in the old game,
Wawacraft:Classic.

** Footnotes

    - [[file:index.org][Return to index.]]
